"""
output_generator.py
--------------------
Generates downloadable Word (.docx) and Excel (.xlsx) deliverables
from LLM outputs, inspection reports, and analytical data.
"""

from datetime import datetime
from pathlib import Path
import uuid
from typing import List, Dict, Any, Optional

from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import openpyxl
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side

OUTPUT_DIR = Path("outputs")
OUTPUT_DIR.mkdir(exist_ok=True)


def generate_approval_note(
    title: str,
    content: str,
    findings: Optional[List[str]] = None,
    signatory: str = "Authorised Signatory / Unit Head",
    classification: str = "INTERNAL — CONFIDENTIAL / RESTRICTED",
) -> Path:
    """
    Generate a formal Word (.docx) Approval Note / Memo for industrial use.

    Returns file Path.
    """
    doc = Document()

    # Set page margins
    sections = doc.sections
    for s in sections:
        s.top_margin = Inches(1.0)
        s.bottom_margin = Inches(1.0)
        s.left_margin = Inches(1.0)
        s.right_margin = Inches(1.0)

    # Document Header Banner
    header_p = doc.add_paragraph()
    header_p.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    run_class = header_p.add_run(f"[{classification}]")
    run_class.font.name = "Arial"
    run_class.font.size = Pt(8.5)
    run_class.font.color.rgb = RGBColor(180, 0, 0)
    run_class.font.bold = True

    # Title
    title_p = doc.add_paragraph()
    title_p.alignment = WD_ALIGN_PARAGRAPH.LEFT
    run_title = title_p.add_run(title)
    run_title.font.name = "Arial"
    run_title.font.size = Pt(18)
    run_title.font.bold = True
    run_title.font.color.rgb = RGBColor(31, 73, 125)

    # Sub-header / Metadata block
    meta_table = doc.add_table(rows=3, cols=2)
    meta_table.autofit = True

    fields = [
        ("Document Ref:", f"SOV-NOTE-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:4].upper()}"),
        ("Date Generated:", datetime.now().strftime("%d %B %Y, %H:%M HRS IST")),
        ("Generated By:", "Sovereign AI Workbench (Air-Gapped Enclave)"),
    ]

    for idx, (lbl, val) in enumerate(fields):
        row_cells = meta_table.rows[idx].cells
        p0 = row_cells[0].paragraphs[0]
        r0 = p0.add_run(lbl)
        r0.font.bold = True
        r0.font.size = Pt(9.5)
        p1 = row_cells[1].paragraphs[0]
        r1 = p1.add_run(val)
        r1.font.size = Pt(9.5)

    doc.add_paragraph()  # spacing

    # Divider line
    div_p = doc.add_paragraph()
    div_r = div_p.add_run("―" * 60)
    div_r.font.color.rgb = RGBColor(200, 200, 200)

    # Executive Summary / Core Body
    h1 = doc.add_heading("1. Executive Summary & Assessment", level=2)
    h1.style.font.color.rgb = RGBColor(31, 73, 125)

    body_p = doc.add_paragraph(content)
    body_p.style.font.name = "Arial"
    body_p.style.font.size = Pt(11)

    # Findings section if provided
    if findings:
        h2 = doc.add_heading("2. Key Findings & Observations", level=2)
        h2.style.font.color.rgb = RGBColor(31, 73, 125)
        for finding in findings:
            p = doc.add_paragraph(finding, style="List Bullet")
            p.style.font.name = "Arial"
            p.style.font.size = Pt(10.5)

    # Recommendation / Action Required
    h3 = doc.add_heading("3. Recommendations & Action Required", level=2)
    h3.style.font.color.rgb = RGBColor(31, 73, 125)

    rec_p = doc.add_paragraph(
        "Based on the analysis above, it is recommended that the competent authority approve "
        "the proposed actions and initiate internal review protocols."
    )
    rec_p.style.font.name = "Arial"
    rec_p.style.font.size = Pt(11)

    # Signature Block
    doc.add_paragraph()
    doc.add_paragraph()
    sig_p = doc.add_paragraph()
    sig_r1 = sig_p.add_run("_________________________________________\n")
    sig_r2 = sig_p.add_run(f"{signatory}\n")
    sig_r2.font.bold = True
    sig_r3 = sig_p.add_run("Sovereign AI Enclave Approval System")
    sig_r3.font.italic = True
    sig_r3.font.size = Pt(9.5)

    out_file = OUTPUT_DIR / f"approval_note_{uuid.uuid4().hex[:8]}.docx"
    doc.save(out_file)
    return out_file


def generate_excel_report(
    title: str,
    rows: List[Dict[str, Any]],
    sheet_name: str = "Analysis Output",
) -> Path:
    """
    Generate a styled Excel (.xlsx) report from tabular data.

    Returns file Path.
    """
    wb = openpyxl.Workbook()
    ws = wb.active
    ws.title = sheet_name[:31]

    # Colors
    header_fill = PatternFill(start_color="1F497D", end_color="1F497D", fill_type="solid")
    header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
    data_font = Font(name="Calibri", size=10)
    thin_border = Border(
        left=Side(style='thin', color='D9D9D9'),
        right=Side(style='thin', color='D9D9D9'),
        top=Side(style='thin', color='D9D9D9'),
        bottom=Side(style='thin', color='D9D9D9'),
    )

    # Title block
    ws.merge_cells("A1:E1")
    title_cell = ws["A1"]
    title_cell.value = f"SOVEREIGN AI WORKBENCH — {title.upper()}"
    title_cell.font = Font(name="Calibri", size=14, bold=True, color="1F497D")
    title_cell.alignment = Alignment(vertical="center")

    ws.merge_cells("A2:E2")
    sub_cell = ws["A2"]
    sub_cell.value = f"Generated on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | Confidential On-Premises Report"
    sub_cell.font = Font(name="Calibri", size=9, italic=True, color="595959")

    ws.row_dimensions[1].height = 25
    ws.row_dimensions[2].height = 18

    if not rows:
        rows = [{"Message": "No data returned for this query", "Timestamp": datetime.now().isoformat()}]

    headers = list(rows[0].keys())

    # Write Headers
    header_row = 4
    ws.row_dimensions[header_row].height = 22

    for col_num, h_text in enumerate(headers, 1):
        cell = ws.cell(row=header_row, column=col_num, value=str(h_text).upper())
        cell.fill = header_fill
        cell.font = header_font
        cell.alignment = Alignment(horizontal="center", vertical="center")

    # Write Data
    for row_idx, record in enumerate(rows, start=header_row + 1):
        ws.row_dimensions[row_idx].height = 19
        for col_idx, key in enumerate(headers, start=1):
            val = record.get(key, "")
            cell = ws.cell(row=row_idx, column=col_idx, value=val)
            cell.font = data_font
            cell.border = thin_border
            if isinstance(val, (int, float)):
                cell.alignment = Alignment(horizontal="right", vertical="center")
            else:
                cell.alignment = Alignment(horizontal="left", vertical="center")

    # Adjust Column Widths
    for col in ws.columns:
        max_len = max(len(str(cell.value or '')) for cell in col)
        col_letter = openpyxl.utils.get_column_letter(col[0].column)
        ws.column_dimensions[col_letter].width = max(max_len + 4, 12)

    out_file = OUTPUT_DIR / f"report_{uuid.uuid4().hex[:8]}.xlsx"
    wb.save(out_file)
    return out_file
