"""
Pydantic schemas and data contracts for the Sovereign AI Workbench Planner and Orchestrator.
"""

from typing import List, Optional, Literal, Dict, Any
from pydantic import BaseModel, Field, ConfigDict


ActionType = Literal["rag", "direct_llm", "clarification", "web_search"]
ToolType = Literal["rag", "llm", "web_search"]


class PlanStep(BaseModel):
    """Represents an atomic execution step within an ExecutionPlan."""
    step: int = Field(..., description="1-indexed sequence number of the step.")
    tool: str = Field(..., description="Tool/Agent to execute: 'rag', 'llm', or 'web_search'.")
    action: str = Field(..., description="Action to perform, e.g., 'retrieve', 'summarize', 'compare', 'answer'.")
    input: str = Field(..., description="Description of the input data or query required for this step.")

    model_config = ConfigDict(extra="ignore")


class ExecutionPlan(BaseModel):
    """The structured decision output generated by the AI Planner."""
    intent: str = Field(..., description="High-level classification of user intent (e.g., 'document_qa', 'general_qa', 'document_summarization', 'document_comparison').")
    requires_rag: bool = Field(..., description="True if private document retrieval is needed.")
    requires_web: bool = Field(default=False, description="True if external web search is needed.")
    steps: List[PlanStep] = Field(..., min_length=1, description="Sequential list of executable steps.")

    model_config = ConfigDict(extra="ignore")


class PlannerResult(BaseModel):
    """
    Standardized decision contract returned by PlannerService.plan().
    Informs the Backend ChatService what action to take next.
    """
    action: Literal["rag", "direct_llm", "clarification", "web_search"] = Field(
        ...,
        description="The determined action: 'rag', 'direct_llm', 'clarification', or 'web_search'."
    )
    query: str = Field(..., description="The user query or normalized query.")
    requires_retrieval: bool = Field(..., description="True if document retrieval via RAG is required.")
    requires_generation: bool = Field(..., description="True if LLM text generation is required.")
    conversation_id: Optional[str] = Field(default=None, description="Optional conversation identifier passed from caller.")
    reason: Optional[str] = Field(default=None, description="Optional reason or intent classification.")
    steps: Optional[List[PlanStep]] = Field(default=None, description="Optional granular execution steps.")

    model_config = ConfigDict(extra="ignore")



class SourceMetadata(BaseModel):
    """Preserves document and page citation metadata across the pipeline."""
    document: str = Field(..., description="Name or identifier of the source document (e.g. 'report.pdf').")
    page: Optional[int] = Field(default=None, description="Page number of the source chunk, if available.")
    chunk_id: Optional[str] = Field(default=None, description="Optional unique identifier for the chunk.")
    score: Optional[float] = Field(default=None, description="Relevance or similarity score.")

    model_config = ConfigDict(extra="ignore")


class RAGChunk(BaseModel):
    """A retrieved chunk of text paired with source metadata."""
    text: str = Field(..., description="Text content extracted from document.")
    source: SourceMetadata = Field(..., description="Source metadata for this chunk.")


class RAGResult(BaseModel):
    """Standardized output from RAG retrieval operations."""
    chunks: List[RAGChunk] = Field(default_factory=list, description="Retrieved text chunks.")
    sources: List[SourceMetadata] = Field(default_factory=list, description="Aggregated unique source references.")


class ChatRequest(BaseModel):
    """Backend input contract for POST /api/chat."""
    message: str = Field(..., min_length=1, description="User query or message.")
    conversation_id: Optional[str] = Field(default=None, description="Optional conversation identifier.")

    model_config = ConfigDict(extra="ignore")


class ChatResponse(BaseModel):
    """Backend output contract for POST /api/chat."""
    answer: str = Field(..., description="Final synthesized response for the user.")
    conversation_id: Optional[str] = Field(default=None, description="Conversation ID.")
    sources: List[SourceMetadata] = Field(default_factory=list, description="List of source citations.")
    plan: Optional[ExecutionPlan] = Field(default=None, description="Optional execution plan for debugging/observability.")

    model_config = ConfigDict(extra="ignore")
