"""
Pydantic schemas and data contracts for the Sovereign AI Workbench Planner and Orchestrator.
"""

from typing import List, Optional, Literal, Dict, Any
from pydantic import BaseModel, Field, ConfigDict


ActionType = Literal["rag", "analytics", "vision", "direct_llm", "multi_tool", "clarification", "web_search"]
ToolType = Literal["rag", "vision", "analytics", "verify", "llm", "web_search"]
TaskType = Literal[
    "document_qa",
    "document_summarization",
    "document_comparison",
    "image_qa",
    "vision_qa",
    "multimodal_qa",
    "calculation_reasoning",
    "incident_investigation",
    "maintenance_analytics",
    "analytics_qa",
    "web_search_qa",
    "general_qa",
    "clarification"
]


class PlanStep(BaseModel):
    """Represents an atomic execution step within an ExecutionPlan."""
    step: int = Field(..., description="1-indexed sequence number of the step.")
    tool: str = Field(..., description="Tool/Agent to execute: 'rag', 'vision', 'analytics', 'verify', 'llm', or 'web_search'.")
    action: str = Field(..., description="Action to perform, e.g., 'retrieve', 'analyze_image', 'analytics', 'verify', 'summarize', 'compare', 'answer', 'calculate', 'synthesize'.")
    input: str = Field(..., description="Description of the input data or query required for this step.")

    model_config = ConfigDict(extra="ignore")


class ExecutionPlan(BaseModel):
    """The structured decision output generated by the AI Planner."""
    intent: str = Field(..., description="High-level classification of user intent (e.g., 'document_qa', 'image_qa', 'multimodal_qa', 'calculation_reasoning', 'incident_investigation', 'maintenance_analytics', 'analytics_qa', 'general_qa').")
    requires_rag: bool = Field(..., description="True if private document retrieval is needed.")
    requires_web: bool = Field(default=False, description="True if external web search is needed.")
    steps: List[PlanStep] = Field(..., min_length=1, description="Sequential list of executable steps.")

    model_config = ConfigDict(extra="ignore")


class PlannerResult(BaseModel):
    """
    Standardized decision contract returned by PlannerService.plan().
    Informs the Backend ChatService what action to take and capability to invoke.
    """
    action: Literal["rag", "analytics", "vision", "direct_llm", "multi_tool", "clarification", "web_search"] = Field(
        ...,
        description="The determined action: 'rag', 'analytics', 'vision', 'direct_llm', 'multi_tool', 'clarification', or 'web_search'."
    )
    query: str = Field(..., description="The user query or normalized query.")
    requires_retrieval: bool = Field(..., description="True if document/diagram retrieval via RAG is required.")
    requires_analytics: bool = Field(default=False, description="True if telemetry/maintenance analytics is required.")
    requires_vision: bool = Field(default=False, description="True if visual P&ID/diagram processing is required.")
    requires_generation: bool = Field(default=True, description="True if LLM text generation is required.")
    
    # SIH PS 26117 Task & Multimodal capability classification
    task_type: str = Field(
        default="general_qa",
        description="Classified task type: 'document_qa', 'image_qa', 'vision_qa', 'multimodal_qa', 'calculation_reasoning', 'incident_investigation', 'maintenance_analytics', 'analytics_qa', 'general_qa', 'clarification'."
    )
    selected_tools: List[str] = Field(
        default_factory=list,
        description="List of selected tool identifiers: e.g. ['rag', 'llm'], ['analytics', 'llm'], ['vision', 'llm'], ['rag', 'analytics', 'verify', 'llm']."
    )
    requires_text: bool = Field(default=True, description="True if textual document/knowledge processing is required.")
    requires_image: bool = Field(default=False, description="Alias indicating if image/P&ID visual processing is required.")
    retrieval_required: bool = Field(default=False, description="Alias indicating if retrieval is required.")
    capability: Optional[str] = Field(default="text", description="Capability category: 'text', 'vision', 'multimodal', 'reasoning', 'analytics'.")
    selected_model: Optional[str] = Field(default=None, description="Configured open-weight model identifier for this task.")
    
    conversation_id: Optional[str] = Field(default=None, description="Optional conversation identifier passed from caller.")
    user_context: Optional[Dict[str, Any]] = Field(default=None, description="Optional user/workspace context (e.g. user_role, allowed_documents).")
    reason: Optional[str] = Field(default=None, description="Explainable reason or intent classification for the decision.")
    fallback_action: Optional[str] = Field(default=None, description="Fallback action if a required tool is unavailable.")
    steps: Optional[List[PlanStep]] = Field(default=None, description="Optional granular execution steps.")

    model_config = ConfigDict(extra="ignore")


class SourceMetadata(BaseModel):
    """Preserves document and page citation metadata across the pipeline."""
    document: str = Field(..., description="Name or identifier of the source document (e.g. 'report.pdf').")
    page: Optional[int] = Field(default=None, description="Page number of the source chunk, if available.")
    chunk_id: Optional[str] = Field(default=None, description="Optional unique identifier for the chunk.")
    score: Optional[float] = Field(default=None, description="Relevance or similarity score.")

    model_config = ConfigDict(extra="ignore")


class EvidenceItem(BaseModel):
    """Structured evidence unit collected during agentic execution."""
    source_type: Literal["document", "vision", "analytics", "web"] = Field(default="document", description="Source modality: 'document', 'vision', 'analytics', 'web'.")
    title: str = Field(..., description="Title or asset name of the source.")
    content: str = Field(..., description="Extracted content or factual observation.")
    page: Optional[int] = Field(default=None, description="Page number if applicable.")
    confidence: float = Field(default=1.0, description="Reliability or similarity confidence (0.0 - 1.0).")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Arbitrary metadata from tool.")

    model_config = ConfigDict(extra="ignore")


class VerificationResult(BaseModel):
    """Result from Evidence Verification Agent (Hallucination Guard)."""
    is_sufficient: bool = Field(..., description="True if evidence is sufficient to answer the query reliably.")
    confidence: float = Field(default=1.0, description="Grounding confidence score (0.0 - 1.0).")
    reason: Optional[str] = Field(default=None, description="Reason if evidence is insufficient or uncertainty explanation.")
    verified_evidence: List[EvidenceItem] = Field(default_factory=list, description="Validated evidence items.")

    model_config = ConfigDict(extra="ignore")


class RAGChunk(BaseModel):
    """A retrieved chunk of text paired with source metadata."""
    text: str = Field(..., description="Text content extracted from document.")
    source: SourceMetadata = Field(..., description="Source metadata for this chunk.")


class RAGResult(BaseModel):
    """Standardized output from RAG retrieval operations."""
    chunks: List[RAGChunk] = Field(default_factory=list, description="Retrieved text chunks.")
    sources: List[SourceMetadata] = Field(default_factory=list, description="Aggregated unique source references.")


class ChatRequest(BaseModel):
    """Backend input contract for POST /api/chat."""
    message: str = Field(..., min_length=1, description="User query or message.")
    conversation_id: Optional[str] = Field(default=None, description="Optional conversation identifier.")
    user_role: Optional[str] = Field(default=None, description="Optional user role / access level.")

    model_config = ConfigDict(extra="ignore")


class ChatResponse(BaseModel):
    """Backend output contract for POST /api/chat."""
    status: Literal["success", "insufficient_evidence", "error", "clarification"] = Field(
        default="success",
        description="Response status: 'success', 'insufficient_evidence', 'error', 'clarification'."
    )
    answer: str = Field(..., description="Final synthesized response for the user.")
    conversation_id: Optional[str] = Field(default=None, description="Conversation ID.")
    sources: List[SourceMetadata] = Field(default_factory=list, description="List of source citations.")
    evidence: List[EvidenceItem] = Field(default_factory=list, description="Structured verified evidence list.")
    confidence: float = Field(default=1.0, description="Grounding / verification confidence score (0.0 - 1.0).")
    steps: Optional[List[PlanStep]] = Field(default=None, description="Executed plan steps.")
    plan: Optional[ExecutionPlan] = Field(default=None, description="Optional execution plan for debugging/observability.")
    reason: Optional[str] = Field(default=None, description="Uncertainty rationale if status is insufficient_evidence.")

    model_config = ConfigDict(extra="ignore")

