"""End-to-End Industrial Knowledge QA & Verification Pipeline.

Combines:
1. search_documents() -> Vector Evidence Retrieval
2. verify_claims() -> Claim Verification Layer
3. Provenance & Citation Formatting
"""

from typing import List, Dict, Any, Optional
from .retriever import search_documents, format_citations
from verification.verifier import verify_claims


def answer_and_verify(
    query: str,
    filters: Optional[Dict[str, Any]] = None,
    telemetry_context: Optional[List[str]] = None,
    top_k: int = 4
) -> Dict[str, Any]:
    """
    Execute full industrial retrieval -> reasoning -> verification flow.

    :param query: Operator query or AI diagnosis request
    :param filters: Optional metadata filters (e.g. {"equipment_tag": "P-101"})
    :param telemetry_context: Live sensor observations / metrics
    :param top_k: Maximum evidence chunks to retrieve
    :return: Full structured response with citations and verification status
    """
    # 1. Retrieve RAG Evidence
    search_res = search_documents(query, filters=filters, top_k=top_k)
    rag_evidence = search_res.get_evidence_texts()

    # 2. Combine with Live Telemetry
    all_evidence = list(rag_evidence)
    if telemetry_context:
        all_evidence.extend(telemetry_context)

    # 3. Formulate synthesized claim/finding based on retrieved evidence
    # (In production, generated by Planner/LLM; here, grounded in knowledge base)
    if search_res.citations:
        primary_citation = search_res.citations[0]
        finding_hypothesis = f"Documentation indicates {primary_citation.document_title} establishes operating thresholds for {primary_citation.equipment_tag or 'equipment'}."
    else:
        finding_hypothesis = f"No documentation found for query '{query}'."

    # 4. Verify the claims against all available evidence
    verification_results = verify_claims(finding_hypothesis, all_evidence)

    # 5. Build formatted citation response
    formatted_citations_md = format_citations(search_res.citations)

    return {
        "query": query,
        "finding": finding_hypothesis,
        "verification": verification_results,
        "citations": [c.to_dict() for c in search_res.citations],
        "citations_formatted": formatted_citations_md,
        "search_metadata": {
            "total_matched": search_res.total_matched,
            "latency_ms": search_res.search_latency_ms
        }
    }
